Minor Update
rocky-linux/rockylinux.org-gatsby pull request #11
Opened 2021-02-07 02:03 UTC by ressonix

- Added Analytics to Site
- Switched Weblate URL in ReadMe badge

2021-02-07 11:41 UTC, hbjydev commented
@ressonix can you update Prettier to ignore the src/i18n folder?
Also, make sure you `pre-commit run --all-files` quickly too to resolve those issues

2021-02-07 11:42 UTC, hbjydev requested changes

2021-02-07 11:42 UTC, hbjydev commented on gatsby-config.js
> +    },
We can't deploy this live until we have a privacy policy. Waiting on @gmkurtzer for that one.

2021-02-07 19:50 UTC, ressonix commented on gatsby-config.js
> +    },
That's fine, I think Neil is working on some things for Matomo today, anyways.

2021-02-09 07:10 UTC, ressonix commented
I'm just going to close this one for now until we get Matomo and the Privacy Policy sorted.

2021-02-09 07:10 UTC, closed without merging