Add missing string in index to translation
rocky-linux/rockylinux.org-gatsby pull request #94
Opened 2021-05-02 05:21 UTC by LuoTR

2021-05-02 05:24 UTC, hbjydev commented
#### 📝Changed routes:


| [**/**](https://rockylinux-37bbrdwgh-resforg.vercel.app/) |
|:-:|
|<a href="https://rockylinux-37bbrdwgh-resforg.vercel.app/"><img src="https://images.weserv.nl?url=https://s.microlink.io/d8lan968r_DK3iQhSO7ZNbHndrZbQbblu-Yg1MFPv8oF22c-0D1n93m-5r_ChcNe_lmNVUUmNPrBUtYZ9otsKA.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/pmQv8xONm3xTLxFP-ZDLavcMekSCShJxjCZb-oPuBig9_wNw4g-Vcv3EL8d6G2b1uaVFc5jLNo_igxQG12jbAQ.png">(view full size)</a> |







Commit 85a36ad3dde45db8a4e6f4f52850a08effbe2dca (https://rockylinux-37bbrdwgh-resforg.vercel.app).

2021-05-09 06:55 UTC, hbjydev requested changes

2021-05-09 06:55 UTC, hbjydev commented on src/components/footer/index.jsx
> +              {translate('links.community-harter')}
```suggestion
              {translate('links.community-charter')}
```

2021-05-09 07:00 UTC, hbjydev requested changes
If we're going to do this, I think we need to add an i18n-next provider now. It will let us specify the _fallback_ language. Currently, on other languages, just the translation string is shown.

2021-05-10 16:41 UTC, LuoTR reviewed
All files seem to be ok now

2021-05-10 16:43 UTC, hbjydev commented
We need your language changes to be peer reviewed but then I'll give it a merge :)

2021-11-04 00:09 UTC, closed without merging